import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import {
  getSessionTokenFromStorage,
  persistTokenFromUri,
  logout
} from "@authdog/browser";

import { useIdentity, useSignin, SignedIn, SignedOut } from "@authdog/react";

export default function Home() {
  const [authenticated, setAuthenticated] = useState(false);

  useEffect(() => {
    persistTokenFromUri();
    if (getSessionTokenFromStorage() !== null) {
      setAuthenticated(true);
    }
  }, []);

  const { user } = useIdentity();
  const { signinUri } = useSignin();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.authdog.com">Authdog</a>
        </h1>
        {authenticated ? (
          <>
            {user ? <h2>Hi {user?.displayName}</h2> : <h3>Loading...</h3>}

            <span
              onClick={() => {
                logout();
              }}
              style={{ cursor: "pointer" }}
            >
              Sign Out
            </span>
          </>
        ) : (
          <a href={String(signinUri)}>Signin</a>
        )}

        <hr />

        <SignedIn>
          <h2>Hi {user?.displayName}</h2>
        </SignedIn>

        <SignedOut>You are not logged in.</SignedOut>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps({ req }: any) {
  return {
    props: {} // will be passed to the page component as props
  };
}
