import {useEffect, useState} from "react"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {getSessionTokenFromStorage, persistTokenFromUri, logout} from "@authdog/sdk-browser"

export default function Home() {

  const [authenticated, setAuthenticated] = useState(false);

  useEffect(() => {
    persistTokenFromUri();
    if (getSessionTokenFromStorage() !== null) {
      setAuthenticated(true);
    }
  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.authdog.com">Authdog</a>
        </h1>
        {authenticated
           ? (
            <span onClick={() => {
              logout({})
            }} style={{ cursor: 'pointer' }}>
              Sign Out
            </span>
            )
            : (
              <a href="https://weblogin.authdog.com?id=a0b7f44c-87a2-4ea6-bc7e-76cf2a019996">Signin</a>
            )
        }


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps({req}: any) {
  // console.log(getParamFromUri(req?.url, "token"))
  return {
    props: {}, // will be passed to the page component as props
  }
}