import Head from "next/head";
import styles from "../styles/Home.module.css";

// import { useIsomorphicAuthdogContext } from "@authdog/authdog-react";

// TODO
// @ts-ignore
// import { withServerSideAuth } from '@authdog/nextjs/api'

export default function Home(props: any) {
  // const ctx = useIsomorphicAuthdogContext();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {JSON.stringify(ctx)} */}
      <a href="https://weblogin.authdog.com?id=a0b7f44c-87a2-4ea6-bc7e-76cf2a019996">Signin</a>
    </div>
  );
}

// export const getServerSideProps = async (context: any) => {
//   // console.log(context);
//   // get user from request

//   return {
//     props: {
//       hello: "Authdog"
//     } // will be passed to the page component as props
//   };
// };

// export const getServerSideProps = withServerSideAuth({ loadUser: true});