import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useIsomorphicAuthdogContext } from "@authdog/authdog-react";

export default function Home(props: any) {
  // const ctx = useIsomorphicAuthdogContext();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {JSON.stringify(ctx)} */}
      Hello
    </div>
  );
}

export const getServerSideProps = async (context: any) => {
  // console.log(context);
  // get user from request

  return {
    props: {
      hello: "Authdog"
    } // will be passed to the page component as props
  };
};
